name: ecomm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile.jpg
    - assets/images/woddy.jpg
    - assets/images/sofa.jpg
    - assets/images/chair.jpg
    - assets/images/bed.jpg
    - assets/images/table.jpg
    - assets/images/wardrobe.jpg
    - assets/images/chair2.jpg
    